"""
Spec Mapper - ALS to SDTM Spec Template Mapper

A module for mapping ALS (Analysis Layer Specification) Excel files
to SDTM Spec templates, generating filled transformation definitions.

This module is integrated into the SIRIUS project to provide end-to-end
functionality from CRF data to final SDTM Specification documents.

Example:
    >>> from src.spec_mapper import SpecMapper
    >>> mapper = SpecMapper(
    ...     als_file="data/output/als.xlsx",
    ...     template_file="data/knowledge_base/template_spec/SDTM_template_IG3.2.xlsx"
    ... )
    >>> result = mapper.process(output_file="data/spec_output/result.xlsx")
    >>> print(f"Processed {result['updates']} mappings")
"""

__version__ = "0.2.0"
__author__ = "SIRIUS Team"

import logging
import os
import shutil
from pathlib import Path
from typing import Any

from .core import ExcelReader, ExcelWriter, Mapper
from .helpers import insert_supp_rows, process_conditional_mappings
from .models import ALSRecord, CellUpdate, ConditionalRecord, SUPPRecord, TemplateRecord
from .utils import ConfigLoader


def get_env_bool(key: str, default: bool = True) -> bool:
    """Get boolean value from environment variable."""
    value = os.getenv(key, str(default)).lower()
    return value in ("true", "1", "yes", "on")


def get_env_path(key: str, default: str) -> str:
    """Get path from environment variable."""
    return os.getenv(key, default)


__all__ = [
    # Models
    "ALSRecord",
    "CellUpdate",
    "ConditionalRecord",
    # Utils
    "ConfigLoader",
    # Core components
    "ExcelReader",
    "ExcelWriter",
    "Mapper",
    "SUPPRecord",
    "SpecMapper",
    "TemplateRecord",
    "map_als_to_spec",
]

logger = logging.getLogger(__name__)


class SpecMapper:
    """
    High-level API for mapping ALS files to SDTM Spec templates.

    This class provides a simple interface to the spec mapping functionality,
    handling all the configuration and coordination internally.

    Attributes:
        als_file: Path to the ALS Excel file
        template_file: Path to the SDTM template Excel file
        als_sheet: Sheet name in ALS file (default: "Sheet1")
        config: Configuration loader instance

    Examples:
        >>> # Basic usage
        >>> mapper = SpecMapper(
        ...     als_file="data/output/als.xlsx",
        ...     template_file="data/knowledge_base/template_spec/SDTM_template_IG3.2.xlsx"
        ... )
        >>> result = mapper.process("data/spec_output/result.xlsx")
        >>> print(f"Generated {result['updates']} cell updates")

        >>> # With custom configuration
        >>> mapper = SpecMapper(
        ...     als_file="data/output/als.xlsx",
        ...     template_file="data/knowledge_base/template_spec/SDTM_template_IG3.2.xlsx",
        ...     config_file="custom_config.yaml"
        ... )
        >>> result = mapper.process(
        ...     output_file="data/spec_output/result.xlsx",
        ...     highlight=True,
        ...     dry_run=False
        ... )
    """

    def __init__(
        self,
        als_file: str | Path,
        template_file: str | Path,
        als_sheet: str | None = None,
        config_file: str | Path | None = None,
        log_level: str | None = None,
    ):
        """
        Initialize the Spec Mapper.

        Args:
            als_file: Path to ALS Excel file (generated by SIRIUS)
            template_file: Path to SDTM template Excel file
            als_sheet: Sheet name in ALS file (default: from ALS_DEFAULT_SHEET env or "eCRF")
            config_file: Optional path to custom config file
            log_level: Logging level (default: from LOG_LEVEL env or "INFO")

        Raises:
            FileNotFoundError: If als_file or template_file doesn't exist
        """
        self.als_file = Path(als_file)
        self.template_file = Path(template_file)

        # Validate files exist
        if not self.als_file.exists():
            raise FileNotFoundError(f"ALS file not found: {als_file}")
        if not self.template_file.exists():
            raise FileNotFoundError(f"Template file not found: {template_file}")

        # Load configuration first (needed for defaults). When no explicit config
        # is given, auto-select the IG-3.4 config for IG-3.4 templates.
        if config_file:
            self.config = ConfigLoader(config_file)
        else:
            self.config = ConfigLoader(self._select_config_path(self.template_file))

        # Determine als_sheet with proper priority:
        # 1. Explicitly passed parameter
        # 2. Environment variable
        # 3. Config file
        # 4. Hardcoded default
        if als_sheet is not None:
            self.als_sheet = als_sheet
        else:
            env_sheet = os.getenv("ALS_DEFAULT_SHEET")
            if env_sheet:
                self.als_sheet = env_sheet
            else:
                self.als_sheet = self.config.get("als_defaults.sheet_name", "Sheet1")

        # Determine log_level with same priority
        if log_level is not None:
            log_level = log_level
        else:
            log_level = os.getenv("LOG_LEVEL", "INFO")

        # Setup logging
        logging.basicConfig(
            level=getattr(logging, log_level.upper()), format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
        )
        self.logger = logging.getLogger(__name__)

        self.logger.info(f"Initialized SpecMapper: ALS={self.als_file.name}, Template={self.template_file.name}")

    @staticmethod
    def _select_config_path(template_file: Path) -> Path:
        """Pick the config matching the template's SDTM IG version.

        Reads CONTENT!B4 (the template's SDTM version cell): IG 3.4 templates use
        ``config_ig34.yaml`` (English Source labels), everything else uses the base
        ``config.yaml``. Falls back to the base config on any error.
        """
        config_dir = Path(__file__).parent / "config"
        base = config_dir / "config.yaml"
        ig34 = config_dir / "config_ig34.yaml"
        if not ig34.exists():
            return base
        try:
            from openpyxl import load_workbook

            wb = load_workbook(template_file, read_only=True, data_only=True)
            try:
                version = ""
                if "CONTENT" in wb.sheetnames:
                    version = str(wb["CONTENT"].cell(row=4, column=2).value or "").strip()
            finally:
                wb.close()
            if version.startswith("3.4"):
                logger.info(f"Detected SDTM IG version {version}; using config_ig34.yaml")
                return ig34
        except Exception as exc:
            logger.warning(f"Template version detection failed ({exc}); using base config.yaml")
        return base

    def process(
        self,
        output_file: str | Path,
        highlight: bool | None = None,
        clear_existing: bool = True,
        dry_run: bool = False,
        create_test_sheets: bool | None = None,
    ) -> dict[str, Any]:
        """
        Process ALS to SDTM Spec mapping and generate output file.

        Args:
            output_file: Path to output Excel file
            highlight: Apply yellow highlighting to new mappings (default: from SPEC_HIGHLIGHT_MAPPINGS env or True)
            clear_existing: Clear existing transformation definitions (default: True)
            dry_run: Preview mode without saving file (default: False)
            create_test_sheets: Create TEST sheets for conditional mappings (default: from config or True)

        Returns:
            Dictionary with processing statistics:
            {
                "als_records": int,           # Number of ALS records read
                "template_records": int,      # Number of template records read
                "updates": int,               # Number of cell updates
                "supp_records": int,          # Number of SUPP rows inserted
                "conditional_records": int,   # Number of conditional mapping groups
                "output_file": str            # Path to output file (if not dry_run)
            }

        Raises:
            Exception: If processing fails
        """
        output_path = Path(output_file)

        # Use environment variable for highlight default if not specified
        if highlight is None:
            highlight = get_env_bool("SPEC_HIGHLIGHT_MAPPINGS", True)

        try:
            # Step 1: Read ALS file
            self.logger.info(f"Reading ALS file: {self.als_file}")
            als_reader = ExcelReader(self.als_file, self.config)
            als_records = als_reader.read_als_records(self.als_sheet)
            self.logger.info(f"✓ Read {len(als_records)} ALS records")

            # Step 2: Read template file
            self.logger.info(f"Reading template file: {self.template_file}")
            template_reader = ExcelReader(self.template_file, self.config)
            template_records = template_reader.read_template_records()
            self.logger.info(f"✓ Read {len(template_records)} template records")

            # Step 3: Perform mapping
            self.logger.info("Performing mapping...")

            # Determine create_test_sheets value (param > config > default True)
            if create_test_sheets is None:
                create_test_sheets = self.config.get("conditional_mapping", {}).get("create_test_sheets", True)

            mapper = Mapper(config=self.config)
            updates, supp_records, conditional_records, codelist_records, unmatched_records = mapper.map(
                als_records, template_records, create_test_sheets=create_test_sheets
            )

            # Collect statistics
            stats: dict[str, Any] = {
                "als_records": len(als_records),
                "template_records": len(template_records),
                "updates": len(updates),
                "supp_records": len(supp_records),
                "conditional_records": len(conditional_records),
                "codelist_records": len(codelist_records),
                "unmatched_records": len(unmatched_records),
            }

            self.logger.info(
                f"✓ Mapping complete: {stats['updates']} updates, "
                f"{stats['supp_records']} SUPP rows, "
                f"{stats['conditional_records']} conditional groups, "
                f"{stats['codelist_records']} codelist entries"
            )

            # Dry run check
            if dry_run:
                self.logger.info("DRY RUN: No changes will be saved")
                stats["output_file"] = str(output_path) + " (dry run)"
                return stats

            # Collect ALS domains (used to limit all write operations)
            als_domains: set[str] = set()
            for rec in als_records:
                if rec.sdtm_domain:
                    for d in rec.sdtm_domain.split("|"):
                        d_stripped = d.strip().upper()
                        if d_stripped:
                            als_domains.add(d_stripped)
            self.logger.info(f"ALS domains: {', '.join(sorted(als_domains))}")

            # Step 4: Write output
            self.logger.info(f"Writing output to: {output_path}")
            output_path.parent.mkdir(parents=True, exist_ok=True)

            # Copy template to output
            shutil.copy2(self.template_file, output_path)

            # Initialize writer
            writer = ExcelWriter(output_path)
            # Render Source (F) labels in the template's language (English for IG 3.4)
            writer.source_label_overrides = self.config.get("source_label_overrides", {}) or {}

            # Insert SUPP rows if any
            domains_with_supp = set()
            if supp_records:
                insert_supp_rows(writer, supp_records, highlight)
                # Track which domains have SUPP records
                for supp_rec in supp_records:
                    domains_with_supp.add(supp_rec.sheet_name)
                self.logger.info(f"✓ Inserted SUPP rows for domains: {', '.join(sorted(domains_with_supp))}")

            # Insert unmatched SDTM variable rows (blue highlight)
            if unmatched_records:
                self._insert_unmatched_rows(writer, unmatched_records)
                self.logger.info(f"✓ Inserted {len(unmatched_records)} unmatched SDTM variable rows")

            # Update existing cells
            writer.update_cells(updates, highlight=highlight, clear_existing=clear_existing)

            # Process conditional mappings if any
            if conditional_records:
                process_conditional_mappings(writer, conditional_records)

            # Update F column (Source) for ALS domain sheets based on transformation definitions
            for domain in sorted(als_domains):
                if domain in writer.workbook.sheetnames:
                    try:
                        writer.update_domain_source_column(domain, highlight=highlight)
                        self.logger.info(f"✓ Updated F column (Source) in {domain} sheet")
                    except Exception as e:
                        self.logger.warning(f"Failed to update F column in {domain}: {e}")

            # Apply fixed variable rules (USUBJID, STUDYID, xxSEQ, VISIT, VISITNUM, DOMAIN)
            # Only apply to domains that actually appear in the ALS2SDTM file
            fixed_variables = self.config.get("fixed_variables", {})
            if fixed_variables:
                for sheet_name in writer.workbook.sheetnames:
                    if len(sheet_name) == 2 and sheet_name.isalpha() and sheet_name.upper() in als_domains:
                        try:
                            writer.apply_fixed_variable_rules(sheet_name, fixed_variables, highlight=highlight)
                            self.logger.info(f"✓ Applied fixed variable rules in {sheet_name} sheet")
                        except Exception as e:
                            self.logger.warning(f"Failed to apply fixed variable rules in {sheet_name}: {e}")

            # Add SUPP information to CONTENT sheet for domains with SUPP
            # Important: Insert from bottom to top to avoid row number shifting issues
            content_sheet_name = self.config.get("template_defaults.content_sheet_name", "CONTENT")

            if domains_with_supp:
                # Sort in reverse order to insert from bottom to top
                for domain in sorted(domains_with_supp, reverse=True):
                    try:
                        writer.add_supp_to_content_sheet(domain, content_sheet_name, highlight=highlight)
                        self.logger.info(f"✓ Added SUPP{domain} to {content_sheet_name} sheet")
                    except Exception as e:
                        self.logger.warning(f"Failed to add SUPP{domain} to {content_sheet_name}: {e}")

                # Fix all hyperlinks in CONTENT sheet after all insertions
                try:
                    writer.fix_content_sheet_hyperlinks(content_sheet_name)
                    self.logger.info(f"✓ Fixed hyperlinks in {content_sheet_name} sheet")
                except Exception as e:
                    self.logger.warning(f"Failed to fix hyperlinks in {content_sheet_name}: {e}")

            # Build domain -> source table mapping from ALS records
            from collections import defaultdict

            domain_sources: dict[str, set[str]] = defaultdict(set)
            for rec in als_records:
                if rec.sdtm_domain:
                    tbl = (rec.metadata_table or rec.table or "").strip()
                    if tbl:
                        # Handle pipe-separated domains (e.g., "CM|PR")
                        for d in rec.sdtm_domain.split("|"):
                            d_stripped = d.strip().upper()
                            if d_stripped:
                                domain_sources[d_stripped].add(tbl)

            # Update CONTENT sheet F column with ALS-derived sources
            try:
                writer.update_content_f_column(
                    content_sheet_name,
                    domain_sources=dict(domain_sources),
                    highlight=highlight,
                )
                self.logger.info(f"✓ Updated F column in {content_sheet_name} sheet")
            except Exception as e:
                self.logger.warning(f"Failed to update F column in {content_sheet_name}: {e}")

            # Detect non-standard domains (in ALS but not in template)
            template_domains = {rec.sheet_name for rec in template_records}
            nonstandard_domains = als_domains - template_domains

            # Add non-standard domains to CONTENT sheet with yellow highlight
            if nonstandard_domains:
                self.logger.info(f"Detected non-standard domains: {', '.join(sorted(nonstandard_domains))}")
                for domain in sorted(nonstandard_domains):
                    # Skip invalid domain names
                    if not domain or len(domain) != 2 or not domain.isalpha():
                        continue
                    try:
                        writer.add_nonstandard_domain_to_content(domain, content_sheet_name)
                        self.logger.info(f"✓ Added non-standard domain '{domain}' to {content_sheet_name}")
                    except Exception as e:
                        self.logger.warning(f"Failed to add non-standard domain '{domain}': {e}")

            # Apply external coding variables (MedDRA, WhoDrug) only for ALS domains
            external_coding = self.config.get("external_coding_variables", {})
            for domain, domain_configs in external_coding.items():
                if domain not in writer.workbook.sheetnames:
                    self.logger.debug(f"Domain '{domain}' not found, skipping external coding variables")
                    continue
                if domain.upper() not in als_domains:
                    self.logger.debug(f"Domain '{domain}' not in ALS, skipping external coding variables")
                    continue

                # Support both list format (new) and dict format (legacy)
                if isinstance(domain_configs, dict):
                    domain_configs = [domain_configs]

                for domain_config in domain_configs:
                    op_type = domain_config.get("type", "insert")
                    var_type = domain_config.get("variable_type", "SUPP")
                    variables = domain_config.get("variables", [])

                    if not variables:
                        continue

                    try:
                        if op_type == "update":
                            # Update existing variables (like AE MedDRA SDTM variables)
                            writer.update_existing_variables(
                                sheet_name=domain, variables=variables, highlight=highlight
                            )
                            self.logger.info(f"✓ Updated {len(variables)} external coding variables in {domain}")
                        else:
                            # Insert new SUPP variables (like CM, MH, PR, AE AEDVER)
                            writer.add_external_coding_variables(
                                sheet_name=domain, variables=variables, variable_type=var_type, highlight=highlight
                            )
                            self.logger.info(
                                f"✓ Added {len(variables)} external coding {var_type} variables to {domain}"
                            )
                    except Exception as e:
                        self.logger.warning(f"Failed to apply external coding variables to {domain}: {e}")

            # Write CODELIST records (TESTCD values from conditional mappings)
            if codelist_records:
                try:
                    writer.write_codelist_records(codelist_records, highlight=highlight)
                    self.logger.info(f"✓ Wrote {len(codelist_records)} CODELIST entries")
                except Exception as e:
                    self.logger.warning(f"Failed to write CODELIST records: {e}")

            # Add CONTENT link formula and sort-key formula only to ALS domain sheets
            for sheet_name in writer.workbook.sheetnames:
                if len(sheet_name) == 2 and sheet_name.isalpha() and sheet_name.upper() in als_domains:
                    try:
                        writer.add_content_link_to_domain(sheet_name, highlight=highlight)
                    except Exception as e:
                        self.logger.warning(f"Failed to add CONTENT link to {sheet_name}: {e}")
                    try:
                        writer.update_domain_sort_key_formula(sheet_name, content_sheet_name, highlight=highlight)
                    except Exception as e:
                        self.logger.warning(f"Failed to update sort-key formula in {sheet_name}: {e}")
            self.logger.info("✓ Updated CONTENT links and sort-key formulas in ALS domain sheets")

            # Set wrap_text for H column (transformation definition) only in ALS domain sheets
            for sheet_name in writer.workbook.sheetnames:
                if len(sheet_name) == 2 and sheet_name.isalpha() and sheet_name.upper() in als_domains:
                    try:
                        writer.set_column_wrap_text(sheet_name, column=8)
                        self.logger.debug(f"✓ Set wrap_text for H column in {sheet_name} sheet")
                    except Exception as e:
                        self.logger.warning(f"Failed to set wrap_text in {sheet_name}: {e}")
            self.logger.info("✓ Set wrap_text for H column in ALS domain sheets")

            # Highlight sheet tabs if enabled
            sheet_highlighting = self.config.get("sheet_highlighting", {})
            if sheet_highlighting.get("enabled", True):
                tab_color = sheet_highlighting.get("color", "FFFF00")
                writer.highlight_modified_sheet_tabs(tab_color)
                self.logger.info("✓ Highlighted modified sheet tabs")

            # Set active sheet (default to CONTENT)
            default_sheet = self.config.get("default_active_sheet", "CONTENT")
            if default_sheet:
                writer.set_active_sheet(default_sheet)
                self.logger.info(f"✓ Set active sheet to '{default_sheet}'")

            # Save and close
            writer.save()
            writer.close()

            self.logger.info(f"✓ Successfully saved to {output_path}")
            stats["output_file"] = str(output_path)

            return stats

        except Exception as e:
            self.logger.error(f"Processing failed: {e}", exc_info=True)
            raise

    def _insert_unmatched_rows(self, writer: ExcelWriter, unmatched_records: list[dict]) -> None:
        """Insert rows for SDTM variables that exist in ALS but not in template.

        These rows are inserted into the corresponding domain sheet with blue
        highlight to differentiate them from template-original rows.

        Args:
            writer: ExcelWriter instance
            unmatched_records: List of dicts with domain, variable, transformation, source, variable_label
        """
        from openpyxl.styles import PatternFill

        blue_fill = PatternFill(start_color="ADD8E6", end_color="ADD8E6", fill_type="solid")

        # Group by domain
        by_domain: dict[str, list[dict]] = {}
        for rec in unmatched_records:
            domain = rec["domain"]
            if domain not in by_domain:
                by_domain[domain] = []
            by_domain[domain].append(rec)

        for domain, records in sorted(by_domain.items()):
            if domain not in writer.workbook.sheetnames:
                self.logger.warning(f"Domain sheet '{domain}' not found, skipping {len(records)} unmatched rows")
                continue

            ws = writer.get_worksheet(domain)

            # Find the last SDTM row
            last_sdtm_row = writer.find_last_row_with_type(
                sheet_name=domain, type_column=9, type_value="SDTM", start_row=14
            )
            insert_row = (last_sdtm_row or 14) + 1

            for i, rec in enumerate(records):
                current_row = insert_row + i
                copy_from_row = insert_row - 1 if insert_row > 14 else 14
                writer.insert_row(
                    sheet_name=domain, row_index=current_row, amount=1, copy_format_from_row=copy_from_row
                )

                # A: Variable Name
                ws.cell(row=current_row, column=1).value = rec["variable"]
                ws.cell(row=current_row, column=1).fill = blue_fill

                # B: Variable Label - leave empty for user to define
                ws.cell(row=current_row, column=2).value = None
                ws.cell(row=current_row, column=2).fill = blue_fill

                # F: Source
                ws.cell(row=current_row, column=6).value = rec.get("source", "CRF")
                ws.cell(row=current_row, column=6).fill = blue_fill

                # H: Transformation definition
                ws.cell(row=current_row, column=8).value = rec.get("transformation", "")
                ws.cell(row=current_row, column=8).fill = blue_fill

                # I: Variable Type
                ws.cell(row=current_row, column=9).value = "SDTM"
                ws.cell(row=current_row, column=9).fill = blue_fill

                # J: Variable Order
                ws.cell(row=current_row, column=10).value = "=ROW()-13"

                self.logger.debug(f"Inserted unmatched row: {domain}.{rec['variable']} at row {current_row}")

            writer.modified_sheets.add(domain)
            self.logger.info(f"Inserted {len(records)} unmatched row(s) in '{domain}' with blue highlight")


def map_als_to_spec(
    als_file: str | Path,
    template_file: str | Path,
    output_file: str | Path,
    als_sheet: str | None = None,
    highlight: bool | None = None,
    clear_existing: bool = True,
    dry_run: bool = False,
    **kwargs,
) -> dict[str, Any]:
    """
    One-line convenience function to map ALS to SDTM Spec.

    This is a simplified interface for quick mapping operations.
    For more control, use the SpecMapper class directly.

    Args:
        als_file: Path to ALS Excel file
        template_file: Path to SDTM template Excel file
        output_file: Path to output Excel file
        als_sheet: Sheet name in ALS file (default: from ALS_DEFAULT_SHEET env or "eCRF")
        highlight: Apply yellow highlighting (default: from SPEC_HIGHLIGHT_MAPPINGS env or True)
        clear_existing: Clear existing definitions (default: True)
        dry_run: Preview mode without saving (default: False)
        **kwargs: Additional arguments passed to SpecMapper

    Returns:
        Statistics dictionary (see SpecMapper.process for details)

    Examples:
        >>> # Simple usage
        >>> stats = map_als_to_spec(
        ...     "data/output/als.xlsx",
        ...     "data/knowledge_base/template_spec/SDTM_template_IG3.2.xlsx",
        ...     "data/spec_output/result.xlsx"
        ... )
        >>> print(f"Processed {stats['updates']} mappings")

        >>> # With options
        >>> stats = map_als_to_spec(
        ...     als_file="data/output/als.xlsx",
        ...     template_file="data/knowledge_base/template_spec/SDTM_template_IG3.2.xlsx",
        ...     output_file="data/spec_output/result.xlsx",
        ...     highlight=True,
        ...     dry_run=True
        ... )
    """
    mapper = SpecMapper(als_file=als_file, template_file=template_file, als_sheet=als_sheet, **kwargs)

    return mapper.process(output_file=output_file, highlight=highlight, clear_existing=clear_existing, dry_run=dry_run)
