"""
Spec Mapper - ALS to SDTM Spec Template Mapper

A module for mapping ALS (Analysis Layer Specification) Excel files
to SDTM Spec templates, generating filled transformation definitions.

This module is integrated into the SIRIUS project to provide end-to-end
functionality from CRF data to final SDTM Specification documents.

Example:
    >>> from src.spec_mapper import SpecMapper
    >>> mapper = SpecMapper(
    ...     als_file="data/output/als.xlsx",
    ...     template_file="data/knowledge_base/template_spec/SDTM_template_IG3.2.xlsx"
    ... )
    >>> result = mapper.process(output_file="data/spec_output/result.xlsx")
    >>> print(f"Processed {result['updates']} mappings")
"""

__version__ = "0.2.0"
__author__ = "SIRIUS Team"

import logging
import os
import shutil
from collections.abc import Callable
from pathlib import Path
from typing import Any

from .core import ExcelReader, ExcelWriter, Mapper
from .helpers import insert_supp_rows, process_conditional_mappings
from .models import ALSRecord, CellUpdate, ConditionalRecord, SUPPRecord, TemplateRecord
from .models.write_result import (
    RECOVERABLE_WRITE_ERRORS,
    STAGE_CONTENT_DOMAINS,
    STAGE_EXTERNAL_CODING,
    STAGE_FIXED_VARIABLE_RULES,
    STAGE_FORMULAS_AND_LINKS,
    STAGE_SOURCE_COLUMNS,
    STAGE_STYLES,
    STAGE_UNMATCHED_ROWS,
    RecoverableWriteError,
    StageWriteResult,
    WriteIssue,
    WriteResult,
)
from .utils import ConfigLoader


def get_env_bool(key: str, default: bool = True) -> bool:
    """Get boolean value from environment variable."""
    value = os.getenv(key, str(default)).lower()
    return value in ("true", "1", "yes", "on")


def get_env_path(key: str, default: str) -> str:
    """Get path from environment variable."""
    return os.getenv(key, default)


__all__ = [
    # Models
    "ALSRecord",
    "CellUpdate",
    "ConditionalRecord",
    # Utils
    "ConfigLoader",
    # Core components
    "ExcelReader",
    "ExcelWriter",
    "Mapper",
    "SUPPRecord",
    "SpecMapper",
    "TemplateRecord",
    "map_als_to_spec",
]

logger = logging.getLogger(__name__)


class SpecMapper:
    """
    High-level API for mapping ALS files to SDTM Spec templates.

    This class provides a simple interface to the spec mapping functionality,
    handling all the configuration and coordination internally.

    Attributes:
        als_file: Path to the ALS Excel file
        template_file: Path to the SDTM template Excel file
        als_sheet: Sheet name in ALS file. Priority: explicit argument,
            ALS_DEFAULT_SHEET, config value, then "Sheet1".
        config: Configuration loader instance

    Examples:
        >>> # Basic usage
        >>> mapper = SpecMapper(
        ...     als_file="data/output/als.xlsx",
        ...     template_file="data/knowledge_base/template_spec/SDTM_template_IG3.2.xlsx"
        ... )
        >>> result = mapper.process("data/spec_output/result.xlsx")
        >>> print(f"Generated {result['updates']} cell updates")

        >>> # With custom configuration
        >>> mapper = SpecMapper(
        ...     als_file="data/output/als.xlsx",
        ...     template_file="data/knowledge_base/template_spec/SDTM_template_IG3.2.xlsx",
        ...     config_file="custom_config.yaml"
        ... )
        >>> result = mapper.process(
        ...     output_file="data/spec_output/result.xlsx",
        ...     highlight=True,
        ...     dry_run=False
        ... )
    """

    def __init__(
        self,
        als_file: str | Path,
        template_file: str | Path,
        als_sheet: str | None = None,
        config_file: str | Path | None = None,
        log_level: str | None = None,
    ):
        """
        Initialize the Spec Mapper.

        Args:
            als_file: Path to ALS Excel file (generated by SIRIUS)
            template_file: Path to SDTM template Excel file
            als_sheet: Sheet name in ALS file. Priority: explicit argument,
                ALS_DEFAULT_SHEET, config value, then "Sheet1".
            config_file: Optional path to custom config file
            log_level: Logging level (default: from LOG_LEVEL env or "INFO")

        Raises:
            FileNotFoundError: If als_file or template_file doesn't exist
        """
        self.als_file = Path(als_file)
        self.template_file = Path(template_file)

        # Validate files exist
        if not self.als_file.exists():
            raise FileNotFoundError(f"ALS file not found: {als_file}")
        if not self.template_file.exists():
            raise FileNotFoundError(f"Template file not found: {template_file}")

        # Load configuration first (needed for defaults). When no explicit config
        # is given, auto-select the IG-3.4 config for IG-3.4 templates.
        if config_file:
            self.config = ConfigLoader(config_file)
        else:
            self.config = ConfigLoader(self._select_config_path(self.template_file))

        # Determine als_sheet with proper priority:
        # 1. Explicitly passed parameter
        # 2. Environment variable
        # 3. Config file
        # 4. Hardcoded default
        if als_sheet is not None:
            self.als_sheet = als_sheet
        else:
            env_sheet = os.getenv("ALS_DEFAULT_SHEET")
            if env_sheet:
                self.als_sheet = env_sheet
            else:
                self.als_sheet = self.config.get("als_defaults.sheet_name", "Sheet1")

        # Determine log_level with same priority
        if log_level is not None:
            log_level = log_level
        else:
            log_level = os.getenv("LOG_LEVEL", "INFO")

        # Setup logging
        logging.basicConfig(
            level=getattr(logging, log_level.upper()), format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
        )
        self.logger = logging.getLogger(__name__)

        self.logger.info(f"Initialized SpecMapper: ALS={self.als_file.name}, Template={self.template_file.name}")

    @staticmethod
    def _select_config_path(template_file: Path) -> Path:
        """Pick the config matching the template's SDTM IG version.

        Reads CONTENT!B4 (the template's SDTM version cell): IG 3.4 templates use
        ``config_ig34.yaml`` (English Source labels), everything else uses the base
        ``config.yaml``. Falls back to the base config on any error.
        """
        config_dir = Path(__file__).parent / "config"
        base = config_dir / "config.yaml"
        ig34 = config_dir / "config_ig34.yaml"
        if not ig34.exists():
            return base
        try:
            from openpyxl import load_workbook

            wb = load_workbook(template_file, read_only=True, data_only=True)
            try:
                version = ""
                if "CONTENT" in wb.sheetnames:
                    version = str(wb["CONTENT"].cell(row=4, column=2).value or "").strip()
            finally:
                wb.close()
            if version.startswith("3.4"):
                logger.info(f"Detected SDTM IG version {version}; using config_ig34.yaml")
                return ig34
        except Exception as exc:
            logger.warning(f"Template version detection failed ({exc}); using base config.yaml")
        return base

    def process(
        self,
        output_file: str | Path,
        highlight: bool | None = None,
        clear_existing: bool = True,
        dry_run: bool = False,
        create_test_sheets: bool | None = None,
        progress_callback: Callable[[str, int, int], None] | None = None,
    ) -> dict[str, Any]:
        """
        Process ALS to SDTM Spec mapping and generate output file.

        Args:
            output_file: Path to output Excel file
            highlight: Apply yellow highlighting to new mappings (default: from SPEC_HIGHLIGHT_MAPPINGS env or True)
            clear_existing: Clear existing transformation definitions (default: True)
            dry_run: Preview mode without saving file (default: False)
            create_test_sheets: Create TEST sheets for conditional mappings (default: from config or True)
            progress_callback: Optional callback receiving a real stage message,
                completed stage count, and total stage count.

        Returns:
            Dictionary with processing statistics:
            {
                "als_records": int,           # Number of ALS records read
                "template_records": int,      # Number of template records read
                "updates": int,               # Number of cell updates
                "supp_records": int,          # Number of SUPP rows inserted
                "conditional_records": int,   # Number of conditional mapping groups
                "output_file": str            # Path to output file (if not dry_run)
            }

        Raises:
            Exception: If processing fails
        """
        output_path = Path(output_file)
        total_stages = 5

        def report_progress(message: str, completed: int) -> None:
            if progress_callback:
                progress_callback(message, completed, total_stages)

        # Use environment variable for highlight default if not specified
        if highlight is None:
            highlight = get_env_bool("SPEC_HIGHLIGHT_MAPPINGS", True)

        try:
            # Step 1: Read ALS file
            report_progress("正在读取 ALS 文件...", 0)
            self.logger.info(f"Reading ALS file '{self.als_file.name}'")
            als_reader = ExcelReader(self.als_file, self.config)
            als_records = als_reader.read_als_records(self.als_sheet)
            self.logger.info(f"✓ Read {len(als_records)} ALS records")

            # Step 2: Read template file
            report_progress("正在读取 SDTM Spec 模板...", 1)
            self.logger.info(f"Reading template file '{self.template_file.name}'")
            template_reader = ExcelReader(self.template_file, self.config)
            template_records = template_reader.read_template_records()
            self.logger.info(f"✓ Read {len(template_records)} template records")

            # Step 3: Perform mapping
            report_progress("正在生成映射计划...", 2)
            self.logger.info("Performing mapping...")

            # Determine create_test_sheets value (param > config > default True)
            if create_test_sheets is None:
                create_test_sheets = self.config.get("conditional_mapping", {}).get("create_test_sheets", True)

            mapper = Mapper(config=self.config)
            updates, supp_records, conditional_records, codelist_records, unmatched_records = mapper.map(
                als_records, template_records, create_test_sheets=create_test_sheets
            )

            # Collect statistics.
            # NOTE: the top-level count fields below are *planned* counts derived
            # from the mapping step. The number of operations that actually wrote
            # to the workbook lives under stats["actual"] / stats["write_result"]
            # and is populated after the write phase completes.
            planned = {
                "cell_updates": len(updates),
                "supp_rows": len(supp_records),
                "unmatched_rows": len(unmatched_records),
                "conditional_mappings": len(conditional_records),
                "codelist_records": len(codelist_records),
            }
            stats: dict[str, Any] = {
                "als_records": len(als_records),
                "template_records": len(template_records),
                # Legacy planned-count fields (kept for backward compatibility).
                "updates": len(updates),
                "supp_records": len(supp_records),
                "conditional_records": len(conditional_records),
                "codelist_records": len(codelist_records),
                "unmatched_records": len(unmatched_records),
                # Explicit planned vs actual split (actual filled in after writes).
                "planned": planned,
            }

            self.logger.info(
                f"✓ Mapping complete: {stats['updates']} updates, "
                f"{stats['supp_records']} SUPP rows, "
                f"{stats['conditional_records']} conditional groups, "
                f"{stats['codelist_records']} codelist entries"
            )

            # Dry run check
            if dry_run:
                self.logger.info("DRY RUN: No changes will be saved")
                empty = WriteResult()
                stats["actual"] = empty.summary()
                stats["write_result"] = empty.to_dict()
                stats["output_file"] = str(output_path) + " (dry run)"
                report_progress("Dry run 完成", total_stages)
                return stats

            # Collect ALS domains (used to limit all write operations)
            als_domains: set[str] = set()
            for rec in als_records:
                if rec.sdtm_domain:
                    for d in rec.sdtm_domain.split("|"):
                        d_stripped = d.strip().upper()
                        if d_stripped:
                            als_domains.add(d_stripped)
            self.logger.info(f"ALS domains: {', '.join(sorted(als_domains))}")

            # Step 4: Write output
            report_progress("正在写入工作簿...", 3)
            self.logger.info(f"Writing output workbook '{output_path.name}'")
            output_path.parent.mkdir(parents=True, exist_ok=True)

            # Copy template to output. A failure here is fatal: there is no
            # workbook to review, so it must propagate and mark the job failed.
            shutil.copy2(self.template_file, output_path)

            # Initialize writer. Opening the workbook is fatal on failure.
            writer = ExcelWriter(output_path)
            # Render Source (F) labels in the template's language (English for IG 3.4)
            writer.source_label_overrides = self.config.get("source_label_overrides", {}) or {}

            # Structured, per-stage record of what was actually written. Every
            # recoverable, item-level write problem is captured here instead of
            # being silently swallowed.
            write_result = WriteResult()

            # Insert SUPP rows if any
            domains_with_supp = set()
            if supp_records:
                write_result.merge_stage(insert_supp_rows(writer, supp_records, highlight))
                # Track which domains have SUPP records
                for supp_rec in supp_records:
                    domains_with_supp.add(supp_rec.sheet_name)
                self.logger.info(f"✓ Processed SUPP rows for domains: {', '.join(sorted(domains_with_supp))}")

            # Insert unmatched SDTM variable rows (blue highlight)
            if unmatched_records:
                write_result.merge_stage(self._insert_unmatched_rows(writer, unmatched_records))
                self.logger.info(f"✓ Processed {len(unmatched_records)} unmatched SDTM variable rows")

            # Update existing cells
            if updates:
                write_result.merge_stage(
                    writer.update_cells(updates, highlight=highlight, clear_existing=clear_existing)
                )

            # Process conditional mappings if any
            if conditional_records:
                write_result.merge_stage(process_conditional_mappings(writer, conditional_records))

            # Update F column (Source) for ALS domain sheets based on transformation definitions
            for domain in sorted(als_domains):
                if domain in writer.workbook.sheetnames:
                    self._guard(
                        write_result,
                        STAGE_SOURCE_COLUMNS,
                        "update_domain_source_column",
                        writer.update_domain_source_column,
                        domain,
                        highlight=highlight,
                        guard_sheet=domain,
                        guard_code="source_update_failed",
                    )

            # Apply fixed variable rules (USUBJID, STUDYID, xxSEQ, VISIT, VISITNUM, DOMAIN)
            # Only apply to domains that actually appear in the ALS2SDTM file
            fixed_variables = self.config.get("fixed_variables", {})
            if fixed_variables:
                for sheet_name in writer.workbook.sheetnames:
                    if len(sheet_name) == 2 and sheet_name.isalpha() and sheet_name.upper() in als_domains:
                        self._guard(
                            write_result,
                            STAGE_FIXED_VARIABLE_RULES,
                            "apply_fixed_variable_rules",
                            writer.apply_fixed_variable_rules,
                            sheet_name,
                            fixed_variables,
                            highlight=highlight,
                            guard_sheet=sheet_name,
                            guard_code="fixed_rule_failed",
                        )

            # Add SUPP information to CONTENT sheet for domains with SUPP
            # Important: Insert from bottom to top to avoid row number shifting issues
            content_sheet_name = self.config.get("template_defaults.content_sheet_name", "CONTENT")

            if domains_with_supp:
                # Sort in reverse order to insert from bottom to top
                for domain in sorted(domains_with_supp, reverse=True):
                    self._guard(
                        write_result,
                        STAGE_FORMULAS_AND_LINKS,
                        "add_supp_to_content_sheet",
                        writer.add_supp_to_content_sheet,
                        domain,
                        content_sheet_name,
                        highlight=highlight,
                        guard_sheet=content_sheet_name,
                        guard_code="content_update_failed",
                    )

                # Fix all hyperlinks in CONTENT sheet after all insertions
                self._guard(
                    write_result,
                    STAGE_FORMULAS_AND_LINKS,
                    "fix_content_sheet_hyperlinks",
                    writer.fix_content_sheet_hyperlinks,
                    content_sheet_name,
                    guard_sheet=content_sheet_name,
                    guard_code="hyperlink_fix_failed",
                )

            # Build domain -> source table mapping from ALS records
            from collections import defaultdict

            domain_sources: dict[str, set[str]] = defaultdict(set)
            for rec in als_records:
                if rec.sdtm_domain:
                    tbl = (rec.metadata_table or rec.table or "").strip()
                    if tbl:
                        # Handle pipe-separated domains (e.g., "CM|PR")
                        for d in rec.sdtm_domain.split("|"):
                            d_stripped = d.strip().upper()
                            if d_stripped:
                                domain_sources[d_stripped].add(tbl)

            # Update CONTENT sheet F column with ALS-derived sources
            self._guard(
                write_result,
                STAGE_SOURCE_COLUMNS,
                "update_content_f_column",
                writer.update_content_f_column,
                content_sheet_name,
                domain_sources=dict(domain_sources),
                highlight=highlight,
                guard_sheet=content_sheet_name,
                guard_code="source_update_failed",
            )

            # Detect non-standard domains (in ALS but not in template)
            template_domains = {rec.sheet_name for rec in template_records}
            nonstandard_domains = als_domains - template_domains

            # Add non-standard domains to CONTENT sheet with yellow highlight
            if nonstandard_domains:
                self.logger.info(f"Detected non-standard domains: {', '.join(sorted(nonstandard_domains))}")
                for domain in sorted(nonstandard_domains):
                    # Skip invalid domain names
                    if not domain or len(domain) != 2 or not domain.isalpha():
                        continue
                    self._guard(
                        write_result,
                        STAGE_CONTENT_DOMAINS,
                        "add_nonstandard_domain_to_content",
                        writer.add_nonstandard_domain_to_content,
                        domain,
                        content_sheet_name,
                        guard_sheet=content_sheet_name,
                        guard_code="content_update_failed",
                    )

            # Apply external coding variables (MedDRA, WhoDrug) only for ALS domains
            external_coding = self.config.get("external_coding_variables", {})
            for domain, domain_configs in external_coding.items():
                if domain not in writer.workbook.sheetnames:
                    self.logger.debug(f"Domain '{domain}' not found, skipping external coding variables")
                    continue
                if domain.upper() not in als_domains:
                    self.logger.debug(f"Domain '{domain}' not in ALS, skipping external coding variables")
                    continue

                # Support both list format (new) and dict format (legacy)
                if isinstance(domain_configs, dict):
                    domain_configs = [domain_configs]

                for domain_config in domain_configs:
                    op_type = domain_config.get("type", "insert")
                    var_type = domain_config.get("variable_type", "SUPP")
                    variables = domain_config.get("variables", [])

                    if not variables:
                        continue

                    if op_type == "update":
                        # Update existing variables (like AE MedDRA SDTM variables)
                        self._guard(
                            write_result,
                            STAGE_EXTERNAL_CODING,
                            "update_existing_variables",
                            writer.update_existing_variables,
                            guard_sheet=domain,
                            guard_code="external_coding_failed",
                            sheet_name=domain,
                            variables=variables,
                            highlight=highlight,
                        )
                    else:
                        # Insert new SUPP variables (like CM, MH, PR, AE AEDVER)
                        self._guard(
                            write_result,
                            STAGE_EXTERNAL_CODING,
                            "add_external_coding_variables",
                            writer.add_external_coding_variables,
                            guard_sheet=domain,
                            guard_code="external_coding_failed",
                            sheet_name=domain,
                            variables=variables,
                            variable_type=var_type,
                            highlight=highlight,
                        )

            # Write CODELIST records (TESTCD values from conditional mappings)
            if codelist_records:
                write_result.merge_stage(writer.write_codelist_records(codelist_records, highlight=highlight))

            # Add CONTENT link formula and sort-key formula only to ALS domain sheets
            for sheet_name in writer.workbook.sheetnames:
                if len(sheet_name) == 2 and sheet_name.isalpha() and sheet_name.upper() in als_domains:
                    self._guard(
                        write_result,
                        STAGE_FORMULAS_AND_LINKS,
                        "add_content_link_to_domain",
                        writer.add_content_link_to_domain,
                        sheet_name,
                        highlight=highlight,
                        guard_sheet=sheet_name,
                        guard_code="formula_write_failed",
                    )
                    self._guard(
                        write_result,
                        STAGE_FORMULAS_AND_LINKS,
                        "update_domain_sort_key_formula",
                        writer.update_domain_sort_key_formula,
                        sheet_name,
                        content_sheet_name,
                        highlight=highlight,
                        guard_sheet=sheet_name,
                        guard_code="formula_write_failed",
                    )
            self.logger.info("✓ Updated CONTENT links and sort-key formulas in ALS domain sheets")

            # Set wrap_text for H column (transformation definition) only in ALS domain sheets
            for sheet_name in writer.workbook.sheetnames:
                if len(sheet_name) == 2 and sheet_name.isalpha() and sheet_name.upper() in als_domains:
                    self._guard(
                        write_result,
                        STAGE_STYLES,
                        "set_column_wrap_text",
                        writer.set_column_wrap_text,
                        sheet_name,
                        guard_sheet=sheet_name,
                        guard_code="style_update_failed",
                        column=8,
                    )
            self.logger.info("✓ Set wrap_text for H column in ALS domain sheets")

            # Highlight sheet tabs if enabled
            sheet_highlighting = self.config.get("sheet_highlighting", {})
            if sheet_highlighting.get("enabled", True):
                tab_color = sheet_highlighting.get("color", "FFFF00")
                self._guard(
                    write_result,
                    STAGE_STYLES,
                    "highlight_modified_sheet_tabs",
                    writer.highlight_modified_sheet_tabs,
                    tab_color,
                    guard_code="style_update_failed",
                )

            # Set active sheet (default to CONTENT)
            default_sheet = self.config.get("default_active_sheet", "CONTENT")
            if default_sheet:
                self._guard(
                    write_result,
                    STAGE_STYLES,
                    "set_active_sheet",
                    writer.set_active_sheet,
                    default_sheet,
                    guard_sheet=default_sheet,
                    guard_code="style_update_failed",
                )

            # Save and close. A save failure is fatal: the artifact is unusable,
            # so it must propagate and mark the job failed.
            report_progress("正在保存工作簿...", 4)
            writer.save()
            writer.close()

            self.logger.info(f"✓ Successfully saved workbook '{output_path.name}'")
            stats["actual"] = write_result.summary()
            stats["write_result"] = write_result.to_dict()
            stats["output_file"] = str(output_path)
            report_progress("工作簿生成完成", total_stages)

            self.logger.info(
                "✓ Write summary: %s/%s written, %s skipped, %s warning(s), %s error(s)",
                write_result.written,
                write_result.attempted,
                write_result.skipped,
                write_result.warning_count,
                write_result.error_count,
            )

            return stats

        except Exception as e:
            # Only the exception *class* is logged — never the message or a
            # traceback — because the Spec job log is user-downloadable.
            self.logger.error("Processing failed (%s)", type(e).__name__)
            raise

    def _guard(
        self,
        result: WriteResult,
        stage: str,
        operation: str,
        fn: Callable[..., int | None],
        *args: Any,
        guard_sheet: str | None = None,
        guard_code: str = "write_failed",
        **kwargs: Any,
    ) -> int | None:
        """Run a single workbook-mutating call and record its real outcome.

        The wrapped method returns the number of workbook mutations it made, so
        this records ``written`` only when the call actually changed the
        workbook (>0). A no-op call (target missing / nothing to do) is recorded
        as ``skipped`` — never as a phantom write.

        A single-call op is atomic from the caller's view: it either returns a
        mutation count (its recoverable preconditions are handled internally by
        returning ``0``) or raises. Only a dedicated
        :class:`RecoverableWriteError` is caught here and recorded as a
        structured error; every other exception — including a bare
        ``ValueError`` — is treated as unknown/fatal and propagates so the job
        is marked ``failed`` (the workbook is never saved as a success). This
        avoids masking a genuine bug behind a broad "recoverable" catch, and
        because recoverable status comes from the return value rather than a
        mid-mutation exception, a partially-mutated workbook is never saved with
        an inaccurate count.
        """
        stage_res = result.stage(stage)
        try:
            ret = fn(*args, **kwargs)
        except RecoverableWriteError as exc:
            stage_res.record_error(
                WriteIssue(
                    code=guard_code,
                    stage=stage,
                    operation=operation,
                    sheet=guard_sheet,
                    detail=type(exc).__name__,
                )
            )
            self.logger.warning("Write op '%s' failed on sheet '%s' (%s)", operation, guard_sheet, type(exc).__name__)
            return None

        mutated = ret if isinstance(ret, int) else (1 if ret else 0)
        if mutated > 0:
            stage_res.record_written()
        else:
            # Exception-free but no mutation: surface as a skip, not a write.
            stage_res.record_skipped(WriteIssue(code="no_op", stage=stage, operation=operation, sheet=guard_sheet))
        return ret

    def _insert_unmatched_rows(self, writer: ExcelWriter, unmatched_records: list[dict]) -> StageWriteResult:
        """Insert rows for SDTM variables that exist in ALS but not in template.

        These rows are inserted into the corresponding domain sheet with blue
        highlight to differentiate them from template-original rows.

        Args:
            writer: ExcelWriter instance
            unmatched_records: List of dicts with domain, variable, transformation, source, variable_label

        Returns:
            A :class:`StageWriteResult`; each unmatched record counts as one
            attempt and is ``written`` after its row is inserted and filled.
            Records whose target domain sheet is missing are ``skipped``.
        """
        from openpyxl.styles import PatternFill

        result = StageWriteResult(stage=STAGE_UNMATCHED_ROWS)
        blue_fill = PatternFill(start_color="ADD8E6", end_color="ADD8E6", fill_type="solid")

        # Group by domain
        by_domain: dict[str, list[dict]] = {}
        for rec in unmatched_records:
            domain = rec["domain"]
            if domain not in by_domain:
                by_domain[domain] = []
            by_domain[domain].append(rec)

        for domain, records in sorted(by_domain.items()):
            if domain not in writer.workbook.sheetnames:
                self.logger.warning(f"Domain sheet '{domain}' not found, skipping {len(records)} unmatched rows")
                for _rec in records:
                    result.record_skipped(
                        WriteIssue(
                            code="domain_not_found",
                            stage=STAGE_UNMATCHED_ROWS,
                            operation="insert_unmatched_row",
                            sheet=domain,
                        )
                    )
                continue

            ws = writer.get_worksheet(domain)

            # Find the last SDTM row
            last_sdtm_row = writer.find_last_row_with_type(
                sheet_name=domain, type_column=9, type_value="SDTM", start_row=14
            )
            insert_row = (last_sdtm_row or 14) + 1

            written_in_domain = 0
            for rec in records:
                current_row = insert_row + written_in_domain
                copy_from_row = insert_row - 1 if insert_row > 14 else 14
                try:
                    writer.insert_row(
                        sheet_name=domain, row_index=current_row, amount=1, copy_format_from_row=copy_from_row
                    )

                    # A: Variable Name
                    ws.cell(row=current_row, column=1).value = rec["variable"]
                    ws.cell(row=current_row, column=1).fill = blue_fill

                    # B: Variable Label - leave empty for user to define
                    ws.cell(row=current_row, column=2).value = None
                    ws.cell(row=current_row, column=2).fill = blue_fill

                    # F: Source
                    ws.cell(row=current_row, column=6).value = rec.get("source", "CRF")
                    ws.cell(row=current_row, column=6).fill = blue_fill

                    # H: Transformation definition
                    ws.cell(row=current_row, column=8).value = rec.get("transformation", "")
                    ws.cell(row=current_row, column=8).fill = blue_fill

                    # I: Variable Type
                    ws.cell(row=current_row, column=9).value = "SDTM"
                    ws.cell(row=current_row, column=9).fill = blue_fill

                    # J: Variable Order
                    ws.cell(row=current_row, column=10).value = "=ROW()-13"
                except RECOVERABLE_WRITE_ERRORS as exc:
                    result.record_error(
                        WriteIssue(
                            code="unmatched_row_insert_failed",
                            stage=STAGE_UNMATCHED_ROWS,
                            operation="insert_unmatched_row",
                            sheet=domain,
                            row=current_row,
                            detail=type(exc).__name__,
                        )
                    )
                    self.logger.warning("Failed to insert unmatched row in '%s' (%s)", domain, type(exc).__name__)
                    continue

                written_in_domain += 1
                result.record_written()
                self.logger.debug(f"Inserted unmatched row: {domain}.{rec['variable']} at row {current_row}")

            if written_in_domain:
                writer.modified_sheets.add(domain)
                self.logger.info(f"Inserted {written_in_domain} unmatched row(s) in '{domain}' with blue highlight")

        return result


def map_als_to_spec(
    als_file: str | Path,
    template_file: str | Path,
    output_file: str | Path,
    als_sheet: str | None = None,
    highlight: bool | None = None,
    clear_existing: bool = True,
    dry_run: bool = False,
    **kwargs,
) -> dict[str, Any]:
    """
    One-line convenience function to map ALS to SDTM Spec.

    This is a simplified interface for quick mapping operations.
    For more control, use the SpecMapper class directly.

    Args:
        als_file: Path to ALS Excel file
        template_file: Path to SDTM template Excel file
        output_file: Path to output Excel file
        als_sheet: Sheet name in ALS file. Priority: explicit argument,
            ALS_DEFAULT_SHEET, config value, then "Sheet1".
        highlight: Apply yellow highlighting (default: from SPEC_HIGHLIGHT_MAPPINGS env or True)
        clear_existing: Clear existing definitions (default: True)
        dry_run: Preview mode without saving (default: False)
        **kwargs: Additional arguments passed to SpecMapper

    Returns:
        Statistics dictionary (see SpecMapper.process for details)

    Examples:
        >>> # Simple usage
        >>> stats = map_als_to_spec(
        ...     "data/output/als.xlsx",
        ...     "data/knowledge_base/template_spec/SDTM_template_IG3.2.xlsx",
        ...     "data/spec_output/result.xlsx"
        ... )
        >>> print(f"Processed {stats['updates']} mappings")

        >>> # With options
        >>> stats = map_als_to_spec(
        ...     als_file="data/output/als.xlsx",
        ...     template_file="data/knowledge_base/template_spec/SDTM_template_IG3.2.xlsx",
        ...     output_file="data/spec_output/result.xlsx",
        ...     highlight=True,
        ...     dry_run=True
        ... )
    """
    mapper = SpecMapper(als_file=als_file, template_file=template_file, als_sheet=als_sheet, **kwargs)

    return mapper.process(output_file=output_file, highlight=highlight, clear_existing=clear_existing, dry_run=dry_run)
